### ISSUE TITLE
uninitialized constant ApplicationMailer

### ISSUE THREAD

**Issue by ajahongir** [publify/publify_core#34]
I am having problem on production:

`NameError: uninitialized constant ApplicationMailer
from /var/www/pro3d/publify_core/app/mailers/notification_mailer.rb:3:in `<top (required)>'`
where is coming ApplicationMailer class?

**Comment by mvz** [comment]
You must use publify_core as a gem inside another Rails application. That application will provide the ApplicationMailer class. If you want something ready to use, please use [publify](https://github.com/publify/publify).
